1. Numpy’da Vektor ve Matrisin farkini tek cumle ile ifade ediniz.
Ans: One-dimensional Numpy arrays are also called vectors, while Numpy arrays with multiple dimensions can be treated as matrices.

In [2]:
#2.10 elemanli bir listeden NumPy Array’i olusturunuz.
import numpy as np
a=np.array([0,1,2,3,4,5,6,7,8,9])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
#3.Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.
b=np.zeros((10,10),dtype=int)
b

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [4]:
#4. Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.
c=np.ones((10,10),dtype=float)
c

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [5]:
#5. Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.
d=np.full((10,10),9,dtype=int)
d

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [6]:
#6. 5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.
e=np.arange(5,25,3)
e

array([ 5,  8, 11, 14, 17, 20, 23])

In [7]:
#7. -1 ile 1 arasinda 30 adet Array olusturunuz.
f=np.linspace(-1,1,30)
f

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

In [8]:
#8. 0 ile 30 arasinda 5x6’lik bir matris olusturun.
g=np.arange(0,30).reshape(5,6)
g

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [9]:
#9. Kosegenleri 1 olan 10x10’luk bir matris olusturunuz.
h=np.eye(10)
h

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [10]:
#10. 0 ile 10 arasinda 5x10’lik bir matris olusturun. (integer) ve bu matrisin; • eleman sayisini • boyut bilgisini/sayisini • satir X sutun bilgisini • veri tipini numpy metodlariyla yazdiriniz.
i=np.random.randint(1,10,(5,10),dtype=int)
print(i)
print(i.size) #eleman sayısı
print(i.shape) #boyut bilgisi
print(i.ndim) #boyut sayısı
print(i.shape) #satırxsütun bilgisi
print(i.dtype) #veri tipi

[[8 9 2 6 1 2 1 4 3 6]
 [2 4 6 4 1 6 4 7 9 5]
 [4 9 2 8 6 8 8 7 8 5]
 [2 9 6 8 4 1 2 5 8 3]
 [1 4 7 8 8 9 7 8 4 1]]
50
(5, 10)
2
(5, 10)
int32


In [11]:
#11. 0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz. (3 boyutlu bir matris olusturulacak)

j=np.random.randint(0,10,(3,4,7))
j

array([[[3, 5, 5, 1, 5, 0, 0],
        [2, 8, 2, 8, 6, 0, 7],
        [5, 8, 3, 0, 8, 4, 1],
        [1, 0, 5, 7, 9, 1, 7]],

       [[2, 4, 6, 8, 8, 2, 1],
        [0, 4, 3, 1, 6, 0, 7],
        [7, 2, 9, 8, 7, 7, 4],
        [9, 3, 6, 2, 4, 7, 6]],

       [[8, 5, 5, 8, 5, 3, 0],
        [7, 8, 9, 6, 9, 0, 4],
        [0, 8, 6, 4, 4, 6, 4],
        [4, 0, 6, 4, 7, 9, 8]]])

In [12]:
#12. Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz. (boyut sayisini degistirin.)
k=np.arange(10).reshape(5,2)
k

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [13]:
#13. 4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.
l=np.arange(5)
m=np.arange(5,10)
n=np.arange(10,15)
o=np.arange(15,20)
p=np.concatenate([l,m,n,o])
p

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:
#14. 2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz,
r=np.array([[1],[2]])
s=np.array([[3,4,5],[6,7,8]])
print(r)
print(s)
t=np.concatenate([r,s],axis=1)
t

[[1]
 [2]]
[[3 4 5]
 [6 7 8]]


array([[1, 3, 4, 5],
       [2, 6, 7, 8]])

In [ ]:
#15. Numpy’da “axis=1” ve “axis=0” arasinda ne fark vardir. Teorik olarak yaziniz?
#ANS:While axis=0 joins as rows, axis=1 joins on column basis. 
# In other words, when axis=1, it combines side by side, when axis=0, it combines bottom-to-bottom. 

In [26]:
#16. Farkli boyutlardaki arraylari satir ve sutun bazli ayri ayri birlestiriniz.

u=np.arange(6).reshape(2,3)
v=np.arange(6,18).reshape(4,3)
y=np.vstack((u,v))
print(u)
print(v)
print(y)
z=np.arange(17,25).reshape(4,2)
z1=np.arange(26,38).reshape(4,3)
z2=np.hstack((z,z1))
print(z)
print(z1)
print(z2)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[17 18]
 [19 20]
 [21 22]
 [23 24]]
[[26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]
[[17 18 26 27 28]
 [19 20 29 30 31]
 [21 22 32 33 34]
 [23 24 35 36 37]]


In [29]:
#17. 10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 5 ayri array olusturunuz.
a=[]
for i in range(10):
    a.append(i)
print(a)
np.split(a,[2,4,6,8])


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [35]:
#18. Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz.Ve bu siralamadan sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.
b=np.random.randint(1,10,(10))
print(b)
b.sort()
b

[2 7 5 1 1 4 5 5 4 1]


array([1, 1, 1, 2, 4, 4, 5, 5, 5, 7])

In [37]:
#19. 20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin.
c=np.random.randint(1,50,(20))
print(c)
print(c[3],c[5],c[7])

[31  7 40 25 38 15 37 21 38 28 32 43  7 24 48 46 36 12  6 26]
25 15 21


In [39]:
#20. 10 elemanli random bir vektor olusturunuz ve bu arrayin 4. elemanini farkli bir sayiyla degistiriniz.
d=np.random.randint(1,10,(10))
print(d)
d[4]=999
print(d)

[4 7 1 2 1 7 3 1 5 4]
[  4   7   1   2 999   7   3   1   5   4]


In [40]:
#21. “Diagonal Matrix” ve “Trace of Matrix” kavramlari hakkinda kucuk bir arastirma yapip bunlarin ne oldugunu belirten kucuk bir aciklama yaziniz.
#In a square matrix, if all the elements other than the elements on the prime diagonal are zero, this matrix is called a diagonal matrix.
#The sum of the elements on the diagonal is called "Trace of Matrix".

In [43]:
#22. 5x5’lik Diagonal bir matris olusturunuz ve Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)
e=np.eye(5,5)
print(e)
print(e[0,0],e[1,1],e[2,2],e[3,3],e[4,4])


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
1.0 1.0 1.0 1.0 1.0


In [44]:
#23. 10 ile 20 arasinda bir vektor olusturunuz. Ve 3. indexten son indexe kadar olan degerleri yazdiriniz.
f=np.arange(10,20)
print(f[3:])

[13 14 15 16 17 18 19]


In [47]:
#24. 10X10 luk bir matris olusturunuz ve ; • 3.satir ve 5.sutuna ulasiniz. 
# • 5.sutunun tum satirlarina ulasiniz. • Tum sutunlarin 2.satirlarina ulasiniz. • tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz. 
# • satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz. 
# • satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz. 
# • sutun indexi sadece 3, 6, 9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz. 
# • 5.indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz.

g=np.arange(100).reshape(10,10)
#print(g[3,5])
#print(g[:,5])
#print(g[2,:])
#print(g[2:7,:])
#print(g[2:5,3:7])
#print(g[5:,:4])
#print(g[:,[3,6,9]])
g[5,5]=1989
print(g)






[[   0    1    2    3    4    5    6    7    8    9]
 [  10   11   12   13   14   15   16   17   18   19]
 [  20   21   22   23   24   25   26   27   28   29]
 [  30   31   32   33   34   35   36   37   38   39]
 [  40   41   42   43   44   45   46   47   48   49]
 [  50   51   52   53   54 1989   56   57   58   59]
 [  60   61   62   63   64   65   66   67   68   69]
 [  70   71   72   73   74   75   76   77   78   79]
 [  80   81   82   83   84   85   86   87   88   89]
 [  90   91   92   93   94   95   96   97   98   99]]


In [52]:
#25. 0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz(tek boyutlu) ve numpy metodlariyla asagidaki 
# islemleri uygulayin; • 20 den buyuk olan kac deger var. • 30’dan kucuk kac deger var • icerisinde 33 gecen kac deger var 
# • olusturulan arrayin tum elemanlarini 5 ile carpin. • olusturulan arrayin tum elemanlarinin 
# 2 ile bolumunden kalanlari yazdiriniz.

h=np.arange(0,50,5)
print(h)
print(h[h > 20])
print(len(h[h > 20]))
print(h[h < 30])
print(len(h[h < 30])) 
print(h[h == 33])
print(len(h[h == 33])) 
print(h * 5)
print(h % 2) 











[ 0  5 10 15 20 25 30 35 40 45]
[25 30 35 40 45]
5
[ 0  5 10 15 20 25]
6
[]
0
[  0  25  50  75 100 125 150 175 200 225]
[0 1 0 1 0 1 0 1 0 1]


In [54]:
#26. 0 ile 1 arasinda 50 elamanli bir array olusturunuz ve; • orlamasini aliniz. 
# • standart sapmasini aliniz. • varyansini aliniz. • median’ini aliniz. • en kucuk degeri bulunuz. 
# • en buyuk degeri bulunuz.

i=np.random.rand(1,50)
print(i.mean())
print(i.std())
print(i.var())
print(np.median(i))
print(np.min(i))
print(np.max(i))

0.5014128165367909
0.28949071691123085
0.08380487517777839
0.510042117155797
0.001267414930952615
0.9588058910015195


In [ ]:
#27. Master odev ; Bir dongu icerisinde random olacak sekilde iki tane 20x20’luk 
# matris uretin ve bu matrislerin farklarini alin. Ve fark matrisinin diagonali,
# -0.1 ile 0.1 arasinda olana kadar bu islemi tekrarlayin. 
# Istenilen matris bulundugunda program dursun ve toplam kac dongunun kuruldugunu, 
#ne kadar sure icinde buldugunu ve istenilen matrisi print ile birlikte ekrana yazdiriniz... 
#Tavsiye: 20 x 20 luk matrisin bulunmasi saatler surebilir. 
#Bu yuzden algoritmanizin dogrulugunu test etmek icin once 4x4, 5x5 
# gibi kucuk matrislerde deneyebilirsiniz. 
#Ve matris sayisisini arttirarak en son 20x20 u deneyebilirsiniz.

import numpy as np
import time
t1=time.time()
a=','
counter=0
while a!='Completed':
    c=[]    
    x=np.random.rand(5,5)
    y=np.random.rand(5,5)
    z=x-y
    counter+=1
    for i in range(len(z)):
        if -0.1<z[i,i]<0.1:            
            c.append(i)
            if len(c)==len(z):
                print(z)
                a='Completed'
print("Number of iterations = ",counter)
t2=time.time()
print("Process completion time = ",t2-t1) 

